settings:
    production : False
    ontologies: 
        - 'ERO'
        - 'SP'
        - 'CHEBI'
        - 'OBI'
        - 'BAO'
        - 'NCBITAXON'
        - 'UBERON'
        - 'EFO'
    tags: 
        - 'step'
        - 'sample'
        - 'reagent'
        - 'equipment'
        - 'input'
        - 'output'
    client-url: http://localhost:4200
    sites:
        protocols_io:
            host: "www.protocols.io"
            ig_query: True
        global:
            host: "$"
            ig_query: False

bioportal:
    url: http://data.bioontology.org
    key: 8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
mongo:
    host: localhost
    database: nanopubs
    port: 27017
